import Link from 'next/link';

export default function TermsPage() {
  return (
    <main className="pt-24 min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold text-[#1a2b4a] mb-8">Terms of Service</h1>
        <div className="prose prose-lg text-gray-700 space-y-6">
          <p>Last updated: January 2025</p>
          <h2 className="text-2xl font-bold text-[#1a2b4a]">Acceptance of Terms</h2>
          <p>By accessing and using GetReadyToPost, you agree to be bound by these Terms of Service and all applicable laws and regulations.</p>
          <h2 className="text-2xl font-bold text-[#1a2b4a]">Use of Service</h2>
          <p>Our service provides AI-powered listing analysis and rewriting. Results are generated by artificial intelligence and should be reviewed before use in any official listing.</p>
          <h2 className="text-2xl font-bold text-[#1a2b4a]">Payment and Refunds</h2>
          <p>All payments are processed securely through Square. Credits are non-refundable once purchased. Each credit entitles you to one listing analysis.</p>
          <h2 className="text-2xl font-bold text-[#1a2b4a]">Intellectual Property</h2>
          <p>You retain ownership of any listing descriptions you submit. AI-generated rewrites are provided for your use and may be used freely in your listings.</p>
          <h2 className="text-2xl font-bold text-[#1a2b4a]">Limitation of Liability</h2>
          <p>GetReadyToPost is not responsible for any errors in AI-generated content. Users are responsible for reviewing and verifying all content before publication.</p>
          <h2 className="text-2xl font-bold text-[#1a2b4a]">Contact</h2>
          <p>For questions about these terms, please contact us through our website.</p>
        </div>
        <div className="mt-12">
          <Link href="/" className="text-[#c9a227] hover:text-[#e8c547] font-semibold">
            Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
